# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/202301040298@mitaoe.ac.in/New Pipeline 2026-06-16 23:27")

# COMMAND ----------

df = spark.read.table("rjrohan.source.orders")
display(df)

# COMMAND ----------

